[package]
name = "adventure_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.11.0"
json = "0.12.4"
lingua = "1.7.1"
natural = "0.5.0"
rand = "0.9.1"
rust-bert = "0.23.0"
rust_tokenizers = "8.1.1"
tch = "0.17.0"

whatlang = "0.16.4"
